### ISSUE TITLE
Building / Installing package

### ISSUE THREAD

**Issue by Chivasrom** [alexhunziker/GrowingSOM#13]
Hello,

I am using R 3.2.5.  I will work on self organizing map. I need to use ''gsom'' package. But when I try to install this package, R says ''Warning in install.packages :package ‘GSOM’ is not available (for R version 3.2.5)''. Is there any solution about this problem??

**Comment by alexhunziker** [comment]
Hello,
this response is probably too late, but i have just updated the installation instructions for this package (see readme.md). Please try it again, and let me know if the problem still persists.

**Comment by soominsomean** [comment]
Hi Alex, I do not get what you mean by "Make sure you are in the package directory then run:" Could you kindly tell me more instruction for this? where exactly should I be running the command R CMD build .?

**Comment by alexhunziker** [comment]
Hi, so if you clone/download the package to some/dir/GrowingSOM, you should execute the R-build command in this directory. 

Note: If R complains about not finding plotrix, install that beforehand (`install.packages("plotrix")` in R)

**Comment by soominsomean** [comment]
I downloaded the GrowingSOM-Master file, unzipped it, and in that directory I opened the command, and typed R CMD build. but then I got the error saying 'R' is not recognized as an internal or external command, operable program or batch file.

**Comment by alexhunziker** [comment]
Oh yes, I forgot to mention in the installation instructions: you need Rtools in order to build R-packages on Windows: https://cran.r-project.org/bin/windows/Rtools/ , this should solve your issue

**Comment by soominsomean** [comment]
Hi, I installed Rtools, and added it to the path, but now I am getting a new error...
Below is the error that I get.

* checking for file './DESCRIPTION' ... OK
* preparing 'GrowingSOM':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
    355 [main] make 3352 C:\Rtools\bin\make.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x770), Win32 error 5.  Terminating.
      1 [main] make 11444 fork: child 3352 - died waiting for dll loading, errno 11
      -----------------------------------
* installing *source* package 'GrowingSOM' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/Users/DOCUME~1/R/R-35~1.3/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c map.c -o map.o
    355 [main] make 3352 C:\Rtools\bin\make.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x770), Win32 error 5.  Terminating.
      1 [main] make 11444 fork: child 3352 - died waiting for dll loading, errno 11
make: fork: Resource temporarily unavailable
ERROR: compilation failed for package 'GrowingSOM'
* removing 'C:/Users/AppData/Local/Temp/Rtmpgvsddu/Rinst2d7c17e06437/GrowingSOM'
In R CMD INSTALL

I googled this error, but I could not find a solution for this... Do you have any advice for me about this issue?

**Comment by alexhunziker** [comment]
i can't reproduce this error, but it seems that this can happen when cylance is installed (according to google). Try to build the package on a different machine, if it succeeds you can copy the .zip file to your original computer and insall it there.

If that does not work, write me an email, and i will send you the .zip file for the package.

**Comment by soominsomean** [comment]
It was indeed the cylance I guess! I tried on other laptop, built zip, moved to the laptop, and the installation is done! Thanks a lot

**Comment by alexhunziker** [comment]
You're welcome
