### ISSUE TITLE
plots(type properties)

### ISSUE THREAD

**Issue by soominsomean** [alexhunziker/GrowingSOM#15]
Hi, Alex,

First of all, thank you for this package.

While I was working  with this package, when I plot(gsom object, type="property")
for some variables, it just shows black and white dots only, even though the legend shows the numbers colored in red/blue. This makes  so it is impossible to see which values indicate which number for these variables. 

Do you have any idea why this happens?

**Comment by alexhunziker** [comment]
I am not aware of that issue. If you tell me how i can reproduce the issue i will have a look why this happens

**Comment by soominsomean** [comment]
unfortunately, I cannot provide the data so I think this cannot be reproducible...
